//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Shoes = new HashSet<Shoe>();
        }
    
        public int IDPerson { get; set; }

        [Required]
        [MaxLength(20, ErrorMessage ="FirstName must be 20 long at most!")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(20, ErrorMessage = "LastName must be 20 long at most!")]
        public string LastName { get; set; }
        public int Age { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Contact must be 50 long at most!")]
        public string Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shoe> Shoes { get; set; }
    }
}
